[package]
name = "raytracer-app"
version = "0.1.0"
authors = ["workstation"]
edition = "2018"

[dependencies]
ray_tracer = { path = ".." }
serde = "0.9.7"
serde_json = "0.9.6"
clap = "2.20"
image = "0.12.3"

[profile.release]
debug=true